### ISSUE TITLE
Capturing pagination w/ Stash

### ISSUE THREAD

**Issue by timkelty** [happycog/VMG-Nested#2]
When using Stash, it's fairly common to need to "capture pagination": https://github.com/croxton/Stash/wiki/Capturing-pagination

When using this method with vmg nested, the pagination tags remain unparsed.

Here's an example:

This works (`channel:entries`):

```
{exp:channel:entries
  paginate="bottom"
  limit="10"
  dynamic="off"
}
  {title}<br>
  {paginate}
    {exp:stash:set name="pagination"}
      {pagination_links}
    {/exp:stash:set}
  {/paginate}
{/exp:channel:entries}

{exp:stash:parse process="end"}
  {exp:stash:get name="pagination"}
{/exp:stash:parse}
```

and this works (`channel:entries` via `vmg_nested`, w/o Stash capture):

```
{exp:vmg_nested:channel:entries
  paginate="bottom"
  limit="10"
  dynamic="off"
}
  {title}<br>
  {paginate}
    {pagination_links}
  {/paginate}
{/exp:vmg_nested:channel:entries}
```

This does NOT work (`{pagination_links}` remains unparsed):

```
{exp:vmg_nested:channel:entries
  paginate="bottom"
  limit="10"
  dynamic="off"
}
  {title}<br>
  {paginate}
    {exp:stash:set name="pagination"}
      {pagination_links}
    {/exp:stash:set}
  {/paginate}
{/exp:vmg_nested:channel:entries}

{exp:stash:parse process="end"}
  {exp:stash:get name="pagination"}
{/exp:stash:parse}
```

**Comment by mrw** [comment]
Thanks for reporting this. Pinging @andrew-kaslick!

**Comment by andrew-kaslick** [comment]
Hi @timkelty,

Can you try adding a `parse="inward"` parameter to the `{exp:vmg_nested:channel:entries}` tag?

**Comment by timkelty** [comment]
Ah that does it! Makes sense now, b/c using `vmg_nested` changes it from being a module to a plugin and therefore changes the default parsing direction to "outward".

And "Makes sense" is a relative term here...we are dealing with EE's template parsing after all.

Thanks!

**Comment by mrw** [comment]
Our pleasure! @andrew-kaslick is a parse order pro. Closing this for now, let us know if anything else comes up.
