### ISSUE TITLE
Using url_title in vmg_nested tag

### ISSUE THREAD

**Issue by esotm** [happycog/VMG-Nested#5]
Is it possible to use the channel entry url_title parameter in the vmg_nested tag?

Like:

`{exp:vmg_nested:channel:entries channel="test" url_title="test_url_title" prefix="nested"}`

It's not working for me. The parameter entry_id does work.

**Comment by esotm** [comment]
Figured it out. Forgot to add dynamic="no" to the vmg tag.

**Comment by andrew-kaslick** [comment]
Glad you were able to get this figured out! Let us know if you have any other questions.
